before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/gj/main.go
    binary: gj
    tags:
      - release
archives:
  - name_template: 'gj_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: go-jira-cli
    description: "simple jira command line client"
    homepage: "https://github.com/rsteube/go-jira-cli"
    license: "MIT"
    tap:
      owner: rsteube
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
scoops:
  - name: go-jira-cli
    description: "simple jira command line client"
    homepage: "https://github.com/rsteube/go-jira-cli"
    license: "MIT"
    bucket:
      owner: rsteube
      name: scoop-bucket
      token: "{{ .Env.GORELEASER_GITHUB_TOKEN }}"
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"

aurs:
  -
    description: "simple jira command line client"
    homepage: "https://github.com/rsteube/go-jira-cli"
    license: "MIT"
    maintainers:
      - rsteube <rsteube@users.noreply.github.com>
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/go-jira-cli-bin.git'

nfpms:
  -
    description: "simple jira command line client"
    homepage: "https://github.com/rsteube/go-jira-cli"
    license: "MIT"
    maintainer: rsteube <rsteube@users.noreply.github.com>
    formats:
      - apk
      - deb
      - rpm
