name: Go

on:
  pull_request:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: shallow clone
      uses: actions/checkout@v2
      if: "!startsWith(github.ref, 'refs/tags/')"

    - name: deep clone
      uses: actions/checkout@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    -
      name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AUR_KEY: ${{ secrets.AUR_KEY }}
        GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
